SELECT DATA, 
       REG_ANS, 
       CD_CONTA_CONTABIL, 
       DESCRICAO, 
       VL_SALDO_FINAL
FROM demonstracoes_contabeis2023
WHERE DESCRICAO = 'EVENTOS INDENIZÁVEIS LÍQUIDOS / SINISTROS RETIDOS'

LIMIT 
    10;

